### ISSUE TITLE
MlcpTask issue, undefined hadoop:get-role-map()

### ISSUE THREAD

**Issue by tzejohn** [rjrudin/ml-gradle#95]
I followed along with the mlcp-project example, and created an MlcpTask.  When the task runs, I am seeing the following error (_Undefined function hadoop:get-role-map_):

```
:importSchemas
mlcp arguments, excluding password: [IMPORT, -host, 10.239.12.22, -port, 8000, -username, people-db-admin, -database, people-db-content, -input_file_path, schemas, -input_file_type, RDF, -output_collections, http://schemas.abbvienet.com/ontologies, -output_permissions, rest-reader, read, rest-writer, update]
16/05/18 12:55:02 INFO contentpump.ContentPump: Hadoop library version: 2.0.0-alpha
16/05/18 12:55:02 INFO contentpump.LocalJobRunner: Content type: XML
java.io.IOException: com.marklogic.xcc.exceptions.XQueryException: XDMP-UNDFUN: (err:XPST0017) Undefined function hadoop:get-role-map()
 [Session: user=people-db-admin, cb=Security [ContentSource: user=people-db-admin, cb=people-db-content [provider: address=/10.239.12.22:8000, pool=1/64]]]
 [Client: XCC/8.0-2, Server: XDBC/8.0-4.2]
in /eval, on line 2
expr:  
	at com.marklogic.contentpump.InputType$6.applyConfigOptions(InputType.java:264)
	at com.marklogic.contentpump.Command$1.createJob(Command.java:326)
	at com.marklogic.contentpump.ContentPump.runCommand(ContentPump.java:191)
	at com.marklogic.contentpump.ContentPump.main(ContentPump.java:67)
Caused by: com.marklogic.xcc.exceptions.XQueryException: XDMP-UNDFUN: (err:XPST0017) Undefined function hadoop:get-role-map()
 [Session: user=people-db-admin, cb=Security [ContentSource: user=people-db-admin, cb=people-db-content [provider: address=/10.239.12.22:8000, pool=1/64]]]
 [Client: XCC/8.0-2, Server: XDBC/8.0-4.2]
in /eval, on line 2
expr:  
	at com.marklogic.xcc.impl.handlers.ServerExceptionHandler.handleResponse(ServerExceptionHandler.java:34)
	at com.marklogic.xcc.impl.handlers.EvalRequestController.serverDialog(EvalRequestController.java:96)
	at com.marklogic.xcc.impl.handlers.AbstractRequestController.runRequest(AbstractRequestController.java:87)
	at com.marklogic.xcc.impl.SessionImpl.submitRequestInternal(SessionImpl.java:437)
	at com.marklogic.xcc.impl.SessionImpl.submitRequest(SessionImpl.java:432)
	at com.marklogic.contentpump.InputType$6.applyConfigOptions(InputType.java:248)
	... 3 more
:importSchemas FAILED
```
If I execute the same command line from the command line mlcp, it works fine.

```
mlcp.bat import -host 10.239.12.22 -port 8000 -username people-db-admin -database people-db-content -input_file_path schemas -input_file_type RDF -output_collections http://schemas.abbvienet.com/ontologies -password admin -output_permissions "rest-reader, read, rest-writer, update"

16/05/18 12:55:32 INFO contentpump.LocalJobRunner: Content type: XML
16/05/18 12:55:32 INFO input.FileInputFormat: Total input paths to process : 1
16/05/18 12:55:34 INFO contentpump.LocalJobRunner:  completed 100%
16/05/18 12:55:34 INFO contentpump.LocalJobRunner: com.marklogic.mapreduce.ContentPumpStats:
16/05/18 12:55:34 INFO contentpump.LocalJobRunner: INPUT_RECORDS: 2
16/05/18 12:55:34 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS: 2
16/05/18 12:55:34 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_COMMITTED: 2
16/05/18 12:55:34 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_FAILED: 0
16/05/18 12:55:34 INFO contentpump.LocalJobRunner: Total execution time: 1 sec

```

Any ideas? I am depending on the same versions of Hadoop and mapreduce as in the example.

**Comment by rjrudin** [comment]
Hey @tzejohn - I believe this is a bug in a version of the mlcp jar file. Let me update the mlcp dependencies in that project - I believe 8.0-5 of mlcp works correctly.

**Comment by tzejohn** [comment]
@rjrudin when I get execute from the command line, I am using the 8.0-4 version of the mlcp client.  Not sure what version of mlcp I am using in gradle.  I don't know what that corresponds to as far as the mlcp-Hadoop version.

**Comment by rjrudin** [comment]
@tzejohn See the above commit. I just tested this out locally, and 8.0-5 mlcp seems to work fine - with one annoyance, which is that it logs an error about not being able to find an executable on Windows, but that does not appear to have any impact on how mlcp behaves. I'm going to ping our Engineering folks about that one. 

Also see the note about needing to bring your own log4j.properties file.

**Comment by tzejohn** [comment]
Thanks @rjrudin , this works well for me now.

**Comment by tzejohn** [comment]
@rjrudin , also, I have seen the same winutils binary error when running the mlcp.sh script under cygwin in windows.  Running the mlcp.bat version does not exhibit the same behavior.
